#include "/Engine/Private/Common.ush"

StructuredBuffer<float4> PreprocessBuffer;
RWStructuredBuffer<float4> VertexAttributeBuffer;
RWBuffer<uint> DepthKeyBuffer;
RWBuffer<uint> IndexValueBuffer;
float4x4 WorldMatrix;
float4x4 ViewMatrix;
float4x4 ViewProjectionMatrix;
int NumGS;
int SH;
float SplatScale;
float OpacityScale;
float3 Scale;

static const float SH_C1 = 0.4886025;
static const float SH_C2[] = { 1.0925484, -1.0925484, 0.3153916, -1.0925484, 0.5462742 };
static const float SH_C3[] = { -0.5900436, 2.8906114, -0.4570458, 0.3731763, -0.4570458, 1.4453057, -0.5900436 };

float InvSquareCentered01(float x)
{
	x -= 0.5;
	x *= 0.5;
	x = sqrt(abs(x)) * sign(x);
	return x + 0.5;
}

uint FloatToSortableUint(float f)
{
	uint fu = asuint(f);
	uint mask = -((int)(fu >> 31)) | 0x80000000;
	return fu ^ mask;
}

float3 ShadeSH(int idx, float3 col,float3 dir, int shOrder, bool onlySH)
{
	dir *= -1;

	float x = dir.x, y = dir.y, z = dir.z;

	// ambient band
	float3 res = col; // col = sh0 * SH_C0 + 0.5 is already precomputed
	if (onlySH)
		res = 0.5;
	// 1st degree
	float3 sh1 = PreprocessBuffer[idx*19+4].xyz;
	float3 sh2 = PreprocessBuffer[idx*19+5].xyz;
	float3 sh3 = PreprocessBuffer[idx*19+6].xyz;
	float3 sh4 = PreprocessBuffer[idx*19+7].xyz;
	float3 sh5 = PreprocessBuffer[idx*19+8].xyz;
	float3 sh6 = PreprocessBuffer[idx*19+9].xyz;
	float3 sh7 = PreprocessBuffer[idx*19+10].xyz;
	float3 sh8 = PreprocessBuffer[idx*19+11].xyz;
	float3 sh9 = PreprocessBuffer[idx*19+12].xyz;
	float3 sh10 = PreprocessBuffer[idx*19+13].xyz;
	float3 sh11 = PreprocessBuffer[idx*19+14].xyz;
	float3 sh12 = PreprocessBuffer[idx*19+15].xyz;
	float3 sh13 = PreprocessBuffer[idx*19+16].xyz;
	float3 sh14 = PreprocessBuffer[idx*19+17].xyz;
	float3 sh15 = PreprocessBuffer[idx*19+18].xyz;
	
	if (shOrder >= 1)
	{
		res += SH_C1 * (-sh1 * y + sh2 * z - sh3 * x);
		// 2nd degree
		if (shOrder >= 2)
		{
			float xx = x * x, yy = y * y, zz = z * z;
			float xy = x * y, yz = y * z, xz = x * z;
			res +=
				(SH_C2[0] * xy) * sh4 +
				(SH_C2[1] * yz) * sh5 +
				(SH_C2[2] * (2 * zz - xx - yy)) * sh6 +
				(SH_C2[3] * xz) * sh7 +
				(SH_C2[4] * (xx - yy)) * sh8;
			// 3rd degree
			if (shOrder >= 3)
			{
				res +=
					(SH_C3[0] * y * (3 * xx - yy)) * sh9 +
					(SH_C3[1] * xy * z) * sh10 +
					(SH_C3[2] * y * (4 * zz - xx - yy)) * sh11 +
					(SH_C3[3] * z * (2 * zz - 3 * xx - 3 * yy)) * sh12 +
					(SH_C3[4] * x * (4 * zz - xx - yy)) * sh13 +
					(SH_C3[5] * z * (xx - yy)) * sh14 +
					(SH_C3[6] * x * (xx - 3 * yy)) * sh15;
			}
		}
	}
	return max(res, 0);
}

float3x3 CalcMatrixFromRotationScale(float4 rot, float3 scale)
{
	float3x3 ms = float3x3(
		scale.x * Scale.x, 0, 0,
		0, scale.y * Scale.y, 0,
		0, 0, scale.z * Scale.z
	);
	
	float x = rot.x;
	float y = rot.y;
	float z = rot.z;
	float w = rot.w;
	
	float3x3 mr = float3x3(
		1-2*(y*y + z*z),   2*(x*y - w*z),   2*(x*z + w*y),
		  2*(x*y + w*z), 1-2*(x*x + z*z),   2*(y*z - w*x),
		  2*(x*z - w*y),   2*(y*z + w*x), 1-2*(x*x + y*y)
	);
	return mul(mr, ms);
}

void CalcCovariance3D(float3x3 rotMat, out float3 sigma0, out float3 sigma1)
{
	float3x3 sig = mul(rotMat,transpose(rotMat));
	sigma0 = float3(sig._m00, sig._m01, sig._m02);
	sigma1 = float3(sig._m11, sig._m12, sig._m22);
}

float2x2 Inverse2x2(float2x2 m)
{
	// 计算行列式
	float det = determinant(m);  // 或者手动计算：m._m00 * m._m11 - m._m01 * m._m10
    
	// 如果行列式为 0，矩阵不可逆，返回单位矩阵
	if (abs(det) < 1e-8)
	{
		return float2x2(1, 0, 0, 1);
	}
    
	// 计算逆矩阵
	float invDet = 1.0 / det;
    
	// 伴随矩阵除以行列式
	return float2x2(
		m._m11 * invDet,  // 00 位置
		-m._m01 * invDet, // 01 位置
		-m._m10 * invDet, // 10 位置
		m._m00 * invDet   // 11 位置
	);
}


float3 CalcCovariance2D(float3 worldPos, float3 cov3d0, float3 cov3d1, float4x4 matrixV, float4x4 matrixP, float2 screenParams)
{
	float4x4 viewMatrix = matrixV;
	float3 viewPos = mul(float4(worldPos, 1),viewMatrix).xyz;

	// this is needed in order for splats that are visible in view but clipped "quite a lot" to work
	float tanFovX = View.TanAndInvTanHalfFOV.x;
	float tanFovY = View.TanAndInvTanHalfFOV.y;
	float limX = 1.3 * tanFovX;
	float limY = 1.3 * tanFovY;
	viewPos.x = clamp(viewPos.x / viewPos.z, -limX, limX) * viewPos.z;
	viewPos.y = clamp(viewPos.y / viewPos.z, -limY, limY) * viewPos.z;

	float focalX = screenParams.x / (2.0 * tanFovX);
	float focalY = screenParams.y / (2.0 * tanFovY);
	
	float3x3 J = float3x3(
		focalX / viewPos.z, 0, -(focalX * viewPos.x) / (viewPos.z * viewPos.z),
		0, focalY / viewPos.z, -(focalY * viewPos.y) / (viewPos.z * viewPos.z),
		0, 0, 0
	);
	float3x3 W = (float3x3)viewMatrix;
	float3x3 T = mul(J,W);
	float3x3 V = float3x3(
		cov3d0.x, cov3d0.y, cov3d0.z,
		cov3d0.y, cov3d1.x, cov3d1.y,
		cov3d0.z, cov3d1.y, cov3d1.z
	);
	float3x3 cov = mul(T, mul(V, transpose(T)));
	
	// Low pass filter to make each splat at least 1px size.
	cov._m00 += 0.3;
	cov._m11 += 0.3;
	return float3(cov._m00, cov._m01, cov._m11);
}

void DecomposeCovariance(float3 cov2d, out float2 v1, out float2 v2)
{
#if 0 // does not quite give the correct results?

	// https://jsfiddle.net/mattrossman/ehxmtgw6/
	// References:
	// - https://www.youtube.com/watch?v=e50Bj7jn9IQ
	// - https://en.wikipedia.org/wiki/Eigenvalue_algorithm#2%C3%972_matrices
	// - https://people.math.harvard.edu/~knill/teaching/math21b2004/exhibits/2dmatrices/index.html
	float a = cov2d.x;
	float b = cov2d.y;
	float d = cov2d.z;
	float det = a * d - b * b; // matrix is symmetric, so "c" is same as "b"
	float trace = a + d;

	float mean = 0.5 * trace;
	float dist = sqrt(mean * mean - det);

	float lambda1 = mean + dist; // 1st eigenvalue
	float lambda2 = mean - dist; // 2nd eigenvalue

	if (b == 0) {
		// https://twitter.com/the_ross_man/status/1706342719776551360
		if (a > d) v1 = float2(1, 0);
		else v1 = float2(0, 1);
	} else
		v1 = normalize(float2(b, d - lambda2));

	v1.y = -v1.y;
	// The 2nd eigenvector is just a 90 degree rotation of the first since Gaussian axes are orthogonal
	v2 = float2(v1.y, -v1.x);

	// scaling components
	v1 *= sqrt(lambda1);
	v2 *= sqrt(lambda2);

	float radius = 1.5;
	v1 *= radius;
	v2 *= radius;

#else

	// same as in antimatter15/splat
	float diag1 = cov2d.x, diag2 = cov2d.z, offDiag = cov2d.y;
	float mid = 0.5f * (diag1 + diag2);
	float radius = length(float2((diag1 - diag2) / 2.0, offDiag));
	float lambda1 = mid + radius;
	float lambda2 = max(mid - radius, 0.1);
	float2 diagVec = normalize(float2(offDiag, lambda1 - diag1));
	diagVec.y = -diagVec.y;
	float maxSize = 4096.0;
	v1 = min(sqrt(2.0 * lambda1), maxSize) * diagVec;
	v2 = min(sqrt(2.0 * lambda2), maxSize) * float2(diagVec.y, -diagVec.x);

#endif
}

[numthreads(256,1,1)]
void Main(
	uint3 Index : SV_DispatchThreadID)
{
	int idx = Index.x;
	if (idx >= NumGS)
		return;

	// Initialize Index Buffer
	IndexValueBuffer[idx] = idx;
	
	float3 gsLocalPos = PreprocessBuffer[idx * 19 + 0].xyz;
	float4 gsRotation = PreprocessBuffer[idx * 19 + 2];
	float3 gsScale = PreprocessBuffer[idx * 19 + 1].xyz;
	float4 gsColor = PreprocessBuffer[idx * 19 + 3];
	
	float4x4 matrixV = ViewMatrix;
	float4x4 matrixP = View.ViewToClip;
	float2 viewParam = View.ViewSizeAndInvSize.xy;
	
	float3 centerWorldPos = mul(float4(gsLocalPos,1.0),WorldMatrix).xyz;
	float4 centerClipPos = mul(float4(centerWorldPos,1.0),ViewProjectionMatrix);
	VertexAttributeBuffer[idx * 3] = centerClipPos;
	
	bool behindCam = centerClipPos.w <= 0;
	
	float opacityScale = 0.6f;
	
	if (!behindCam)
	{
		float3x3 splatRotScaleMat = CalcMatrixFromRotationScale(gsRotation,gsScale);

		float3 cov3d0,cov3d1;
		CalcCovariance3D(splatRotScaleMat,cov3d0,cov3d1);

		float splatScale2 = SplatScale * SplatScale;
		cov3d0 *= splatScale2;
		cov3d1 *= splatScale2;
		
		float3 cov2d = CalcCovariance2D(
			gsLocalPos,cov3d0,cov3d1,
			matrixV,
			matrixP,
			viewParam);
		
		float2 axis1,axis2;
		DecomposeCovariance(cov2d,axis1,axis2);
		VertexAttributeBuffer[idx * 3 + 1] = float4(axis1,axis2);
		
		float3 worldViewDir = View.WorldViewOriginHigh.xyz - centerWorldPos;
		float objViewDir = mul(worldViewDir,(float3x3)WorldMatrix);
		objViewDir = normalize(objViewDir);

		float3 outColor = ShadeSH(idx,gsColor,objViewDir,SH,0);
		// float opacity = min(InvSquareCentered01(gs_Color.w) * opacityScale, 65000);
		float opacity = gsColor.w * OpacityScale * OpacityScale;
		VertexAttributeBuffer[idx * 3 + 2] = float4(outColor,opacity);
	}
	float depth = centerClipPos.z / centerClipPos.w;
	DepthKeyBuffer[idx] = FloatToSortableUint(depth);
}